# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-24 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_auto_20190523_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('disliked', 'Disliked'), ('liked', 'Liked')], max_length=15, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='products.Product')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to='accounts.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='user_ratings',
            field=models.ManyToManyField(related_name='ratings', through='products.UserRating', to='accounts.UserProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together=set([('product', 'user_profile')]),
        ),
    ]
